Console.BackgroundColor = ConsoleColor.White;
Console.ForegroundColor = ConsoleColor.DarkMagenta;
Console.WriteLine("TIPO TOBI-NARUTO");
Console.ResetColor();
Console.WriteLine("");
Console.ForegroundColor = ConsoleColor.Yellow;
Console.WriteLine("Ye, ye, Sid no beat");
Console.WriteLine("Ya, ya, MHzin novamente, o do flowzin"); 
Console.WriteLine("diferente");
Console.WriteLine("Brota que a tropa descarrega o pente");
Console.ResetColor();
Console.WriteLine("");
Console.WriteLine("");
Console.ForegroundColor = ConsoleColor.Red;
          Console.WriteLine("Máscara na cara, ninja da quebrada");
          Console.WriteLine("Olha no meu olho, é só Kamui nessa safada (nessa safada)");
          Console.WriteLine("Se tocar no manto, nóis já lança a Nove Caudas (a Nove Caudas)");
          Console.WriteLine("Passo na sua vila, eu juro que não sobra nada");
          Console.ResetColor();
          Console.WriteLine("");
          Console.ForegroundColor = ConsoleColor.Black;

          Console.WriteLine("Olha no meu olho, é só Kamui nessa safada (nessa safada)");
          Console.WriteLine("Se tocar no manto, nóis já lança a Nove Caudas (a Nove Caudas)");
          Console.WriteLine("Passo na sua vila, eu juro que não sobra nada");
          Console.WriteLine("");
           Console.WriteLine("");
          Console.WriteLine("Cheguei bolado aqui nessa vila");
          Console.WriteLine("Kurama ativada com a Invocação");
          Console.WriteLine("No olho da Raposa, tu vê o Sharingan");
          Console.WriteLine("Porque ela tá sob minha dominação");
          Console.WriteLine("");
           Console.WriteLine("");
          Console.WriteLine("Minato é culpado do fim da minha mina");
          Console.WriteLine("Por isso que agora é só retaliação");
          Console.WriteLine("Eu pego e atiro o Narutin pra cima");
          Console.WriteLine("Só pra tu entender minha situação");
          Console.WriteLine("");
           Console.WriteLine("");
          Console.WriteLine("Ele vê o cara mascarado, sinistro e bolado");
          Console.WriteLine("Todo encapuzado, Sharingan ligado");
          Console.WriteLine("Kushina no faro, Kamui ativado");
          Console.WriteLine("E aí Minato, cê não era o brabo?");
          Console.WriteLine("");
           Console.WriteLine("");
          Console.WriteLine("Preso nas correntes, é o fim da sua vida");
          Console.WriteLine("Pra tu e sua família, esse é o final");
          Console.WriteLine("Hokage não aguenta, o renegado é pica");
          Console.WriteLine("Tu sente só Chupadão Dimensional");
          Console.WriteLine("");
           Console.WriteLine("");
          Console.WriteLine("Sorte que eu não tenho Susano'o pois");
          Console.WriteLine("Quando a pedra me esmagou");
          Console.WriteLine("Eu emprestei o meu olho pro Kakashi");
          Console.WriteLine("Mas sabe que foi quando a vida mudou");
          Console.WriteLine("Meu mundo se acabou");
          Console.WriteLine("Quando perdi quem eu amava de verdade");
          Console.WriteLine("");
           Console.WriteLine("");
          Console.WriteLine("E é normal que eu virei um cara mal");
          Console.WriteLine("Com o Sharingan anormal");
          Console.WriteLine("Já não sabem se é disfarce ou se é o Madara real");
          Console.WriteLine("E eu vivo colecionando essa Bijuu (essa Bijuu)");
          Console.WriteLine("Matatabi, Saiken, raptando o Shukaku");
          Console.WriteLine("");
           Console.WriteLine("");
          Console.WriteLine("Pega o Kokuou e manipula o Son Goku, hey");
          Console.WriteLine("Choumei, Hachibi, se pá também o Isobu");
          Console.WriteLine("Colecionando Bijuu, o pai tá full");
          Console.WriteLine("Cheio de cauda, fala uhh");
          Console.WriteLine("Quem que tá forte? Jogando no porte");
          Console.WriteLine("Com todo holofote, lançando Genju");
          Console.WriteLine("");
           Console.WriteLine("");
          Console.WriteLine("Hoje que nóis invade, ye (invade, ye)");
          Console.WriteLine("O meu Kamui tá chave, ye (tá chave, ye)");
          Console.WriteLine("Tipo uma viagem (tipo uma viagem)");
          Console.WriteLine("Mudando de fase, ye, tô em outra vibe");
          Console.WriteLine("");
           Console.WriteLine("");
          Console.WriteLine("Porque o Kamui é mó chave, ye");
          Console.WriteLine("Rebola pro papi, ye");
          Console.WriteLine("Usa o Edo Tensei e já revive esses Mandrake");
          Console.WriteLine("Taca fogo nesse baile, quem que só usa uma Cartier, ye?");
          Console.WriteLine("Dirigindo esse Bugatti, ye");
          Console.WriteLine("Quem que manipula a Akatsuki, ye?");
          Console.WriteLine("");
           Console.WriteLine("");
          Console.WriteLine("Cê não acerta e nóis não erra, não");
          Console.WriteLine("Quando me vê mascarado, bolado");
          Console.WriteLine("Você me chama de vilão (chama de vilão)");
          Console.WriteLine("Tomoe tá girando e nós passa a visão (passa a visão)");
          Console.WriteLine("É que eu sou ninja, meu mano no CAP (mano no CAP)");
          Console.WriteLine("Não tô de blefe, só reparar no selo da minha mão (ahn, ahn, ahn, yeah)");
          Console.WriteLine("(Ahn, ahn, ahn, yeah)");
          Console.WriteLine("");
           Console.WriteLine("");
          Console.WriteLine("Eu broto na cúpula, na contenção");
          Console.WriteLine("Aê 5 Kages, vou passar a visão");
          Console.WriteLine("Ou passa a Bijuu, e se não entregar pra nóis");
          Console.WriteLine("É Quarta Guerra Ninja e vai ter trocação");
          Console.WriteLine("Agora o Sasuke já tá na minha mão");
          Console.WriteLine("Se liga Raikage, cê é mó vacilão");
          Console.WriteLine("E aí Mizukage, cê tem mó peitão");
          Console.WriteLine("Só valeu e falou, fui pra outra dimensão");
          Console.WriteLine("");
           Console.WriteLine("");
          Console.WriteLine("E aí Konan, cê não vai me tocar");
          Console.WriteLine("Nesse origami é só ratatatá");
          Console.WriteLine("O Pain e o Nagato, onde é que eles tá?");
          Console.WriteLine("Vou te mandar pra esse memo lugar");
          Console.WriteLine("Fala Kakashi, paga de senpai");
          Console.WriteLine("Quando era criança cê só debochava");
          Console.WriteLine("Agora que cê tá aqui na dimensão do pai");
          Console.WriteLine("Tenta copiar minha levada");
          Console.WriteLine("");
           Console.WriteLine("");
          Console.WriteLine("Minha levada, minha levada");
          Console.WriteLine("Tenta copiar essa levada");
          Console.WriteLine("É o Tobi? Ou Obito?");
          Console.WriteLine("Ou é o Uchiha Madara?");
          Console.WriteLine("");
           Console.WriteLine("");
          Console.WriteLine("Joguei Kurama na vila");
          Console.WriteLine("Eu sou culpado do fim dos Uchihas");
          Console.WriteLine("Eu dei início nessa Guerra Ninja");
          Console.WriteLine("Manipulei geral com meu Sharingan");
          Console.ResetColor();
          Console.WriteLine("");
           Console.WriteLine("");
           Console.ForegroundColor = ConsoleColor.Red;
          Console.WriteLine("Máscara na cara, ninja da quebrada");
          Console.WriteLine("Olha no meu olho, é só Kamui nessa safada");
          Console.WriteLine("Se tocar no manto, nóis já lança a Nove Caudas");
          Console.WriteLine("Dimensão em dimensão");
          Console.WriteLine("Então supera, que eu juro que eu vou lançar a braba");
          Console.ResetColor();
          Console.WriteLine("");
           Console.WriteLine("");
           Console.ForegroundColor = ConsoleColor.Red;
          Console.WriteLine("Máscara na cara, ninja da quebrada");
          Console.WriteLine("Olha no meu olho, é só Kamui nessa safada");
          Console.WriteLine("Se tocar no manto, nóis já lança a Nove Caudas");
          Console.WriteLine("Passo na sua vila, eu juro que não sobra nada");
          Console.ResetColor();